# Generated by Django 4.2 on 2023-04-11 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0002_cart_rename_products_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='product_quantity',
            new_name='cardID',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='customer_name',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='product_name',
        ),
        migrations.AddField(
            model_name='cart',
            name='customerID',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='cart',
            name='date_created',
            field=models.DateField(default=1),
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('cart_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inventory_app.cart')),
                ('customer_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
            bases=('inventory_app.cart',),
        ),
    ]
