# Generated by Django 4.2 on 2023-04-11 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0003_rename_product_quantity_cart_cardid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='date_created',
            field=models.DateField(default='11/04/2023'),
        ),
    ]
